---
apiVersion: v1
kind: Pod
metadata:
  name: firstpod
  labels: 
    version: v1
spec:
  containers:
  - name: firstpod
    image: gcr.io/kuar-demo/kuard-amd64:1
    ports:
      - containerPort: 8080
        name: http
        protocol: TCP
