---
apiVersion: v1
kind: Pod
metadata:
  name: firstpod
  labels:
    version: v1
spec:
  containers:
    - name: firstpod
      image: ongoonku/kuard-amd64:1
      livenessProbe:
        httpGet:
          path: /healthy
          port: 8080
        initialDelaySeconds: 5
        timeoutSeconds: 2
        periodSeconds: 5
        failureThreshold: 1
