---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kuard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kuard
  template:
    metadata:
      labels:
        app: kuard
    spec:
      containers:
        - name: kuard
          image: ongoonku/kuard-amd64:1
          livenessProbe:
            httpGet:
              path: /healthy
              port: 8080
